[[project]]
name = "Lorem Ipsum"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["lorem", "ipsum"]
links = [
    { name = "website", url = "https://example.com" },
    { name = "github", url = "https://example.com" },
    { name = "docs", url = "https://example.com" },
    { name = "wiki", url = "https://example.com" },
]
